## numpy array operations


In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9]);
print("basic slicing ",arr[1:5]);
print("basic slicing with step ",arr[1:5:2]);

basic slicing  [2 3 4 5]
basic slicing with step  [2 4]


In [9]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]]);

print("specific element ",arr_2d[1,2]);
print("entire row ",arr_2d[2]);
print("entire row ",arr_2d[:,2]);

specific element  6
entire row  [7 8 9]
entire row  [3 6 9]


## sorting concept

In [13]:
unsorted = np.array([3,7,5,3,1,0,9]);
print("sorted array ",np.sort(unsorted));

unsorted_2d = np.array([[1,9,3],
                        [4,0,2],
                        [1,9,3]]);

print("sorted 2d array ",np.sort(unsorted_2d,axis=0));
print("sorted 2d array ",np.sort(unsorted_2d,axis=1));



sorted array  [0 1 3 3 5 7 9]
sorted 2d array  [[1 0 2]
 [1 9 3]
 [4 9 3]]
sorted 2d array  [[1 3 9]
 [0 2 4]
 [1 3 9]]


## filtering

In [17]:
number = np.array([1,2,4,4,6,7,9,8,5]);

even_number = number[number % 2 == 0];

print("even number ",even_number);

even number  [2 4 4 6 8]


## filter with mask

In [19]:
mask = number > 5
print("number greater then 5 ",number[mask])

number greater then 5  [6 7 9 8]


### fancy indexing vs np.where()

In [23]:
indices = [1,2,3];
print("number ",number[indices]);

where_result = np.where(number>5);
print("np where ",number[where_result]);

number  [2 4 4]
np where  [6 7 9 8]


In [27]:
condition_array = np.where(number>5 , number*2,number);  # number > 5 then to number * 2 other wise give me number 
cond_boolean = np.where(number > 5 , "true","false");
print(cond_boolean)
print(condition_array);

['false' 'false' 'false' 'false' 'true' 'true' 'true' 'true' 'false']
[ 1  2  4  4 12 14 18 16  5]


## adding and removing data

In [29]:
arr1 = np.array([1,2,3]);
arr2 = np.array([4,5,6]);

combined = np.concatenate((arr1,arr2))
print(combined);

[1 2 3 4 5 6]


### compatibility

In [33]:
a = np.array([1,2,3]);
b = np.array([4,5,6]);

print("compatibility shapes ",a.shape == b.shape);

compatibility shapes  True


In [36]:
original = np.array([[1,2],[3,4]]);
new_row = np.array([[5,6]]);

Add_new_row = np.vstack((original,new_row));

print(original);

print(Add_new_row);

new_col = np.array([[7],[8]]);

Add_new_col = np.hstack((original,new_col));

print(Add_new_col);

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [37]:
# delete operation

arr = np.array([1,2,3,4]);

deleted = np.delete(arr,2);

print(deleted)

[1 2 4]
