welcome to jupyter

learn about numpy

In [4]:
import numpy as np

creating array from list

In [8]:
arr_1d = np.array([1,2,3,4,5])
print("1d array ",arr_1d);

arr_2d = np.array([[1,2,3],[4,5,6]]);
print("2d array ",arr_2d);

1d array  [1 2 3 4 5]
2d array  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [11]:
py_list = [1,2,3]
print("python list multiplication ",py_list*2);

np_array = np.array([1,2,3]);
print("python array multiplication ",np_array*2);


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("list operation time: ",time.time()-start);

start = time.time()
np_array = np.arange(1000000)*2 # start,stop,end
print("numpy operation time ",time.time()-start);

python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication  [2 4 6]
list operation time:  0.14995527267456055
numpy operation time  0.0070226192474365234


### creating array from scratch

In [17]:
zeros = np.zeros((3,4));
print("zeros array \n",zeros);

ones = np.ones((2,3));
print("ones array: ",ones);

full = np.full((2,2),7);
print("full array \n",full) # matrix row,column size and constant value is 7

random = np.random.random((2,3)); # matrix with random value
print("random array \n",random);

sequence = np.arange(0,10,2);
print("sequence array \n",sequence); # start,stop,steps

zeros array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:  [[1. 1. 1.]
 [1. 1. 1.]]
full array 
 [[7 7]
 [7 7]]
random array 
 [[0.70491395 0.84266333 0.40611021]
 [0.31228293 0.16052917 0.9189828 ]]
sequence array 
 [0 2 4 6 8]


### vector matrix and tensor


In [21]:
vector = np.array([1,2,3])
print("vector ",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix ",matrix);

tensor = np.array([
                   [[1,2],[3,4]],
                   [[5,6],[7,8]]
                   ]);
print("tensor: ",tensor);

vector  [1 2 3]
matrix  [[1 2 3]
 [4 5 6]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties


In [31]:
arr = np.array([[1,2,3],[4,5,6]]);
print("shape is ",arr.shape);
print("dimension ",arr.ndim);
print("size: ",arr.size);
print("data type: ",arr.dtype);



shape is  (2, 3)
dimension  2
size:  6
data type:  int32


### array shaping

In [37]:
arr = np.arange(12)
print("original array",arr)

reshaped = arr.reshape((3,4))
print("reshaped array ",reshaped);

flattened = arr.flatten()
print("flattened array ",flattened);

# ravel (return original , instead of copy)
raveled = reshaped.ravel();
print("raveled array ",raveled);

#transpose
transpose = reshaped.T;
print("transpose array ",transpose)

original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
